// Stamps the release chosen by semantic-release into the user-visible constants
// shown in the "About HoneyHold" modal: the VERSION string and the LATEST_RELEASE
// object (title, date, link, and highlights of the newest changelog entry).
//
// Invoked by @semantic-release/exec during the `prepare` step:
//   node scripts/sync-version.mjs <version>
//
// @semantic-release/changelog runs its `prepare` before this one (see the plugin
// order in .releaserc.json), so CHANGELOG.md already holds the new entry by the
// time we parse it here. The updated config.ts is committed back by
// @semantic-release/git.
import { readFileSync, writeFileSync } from 'node:fs';

const version = process.argv[2];
if (!version) {
  console.error('sync-version: missing <version> argument');
  process.exit(1);
}

const configPath = 'frontend/src/lib/config.ts';
const changelogPath = 'CHANGELOG.md';

let config = readFileSync(configPath, 'utf8');

// --- 1. VERSION -----------------------------------------------------------
const withVersion = config.replace(
  /export const VERSION = '[^']*';/,
  `export const VERSION = '${version}';`,
);
if (withVersion === config) {
  console.error(`sync-version: could not find the VERSION constant in ${configPath}`);
  process.exit(1);
}
config = withVersion;

// --- 2. LATEST_RELEASE ----------------------------------------------------
const release = parseLatestRelease(readFileSync(changelogPath, 'utf8'));
if (!release) {
  console.error(`sync-version: could not parse a release entry from ${changelogPath}`);
  process.exit(1);
}

const markerStart = '// LATEST_RELEASE:start';
const markerEnd = '// LATEST_RELEASE:end';
const blockPattern = new RegExp(`${markerStart}[\\s\\S]*?${markerEnd}`);
if (!blockPattern.test(config)) {
  console.error(`sync-version: could not find the LATEST_RELEASE block in ${configPath}`);
  process.exit(1);
}
config = config.replace(blockPattern, renderReleaseBlock(release));

writeFileSync(configPath, config);
console.log(`sync-version: ${configPath} -> ${version} (${release.notes.length} note(s))`);

// --- helpers --------------------------------------------------------------

/** Extract the newest release (the first `## ` block) from a changelog. */
function parseLatestRelease(changelog) {
  // Slice from the first `## ` heading up to the next one (or EOF).
  const all = changelog.split('\n');
  const start = all.findIndex((line) => /^##\s+/.test(line));
  if (start === -1) return null;
  const rest = all.slice(start + 1).findIndex((line) => /^##\s+/.test(line));
  const end = rest === -1 ? all.length : start + 1 + rest;
  const lines = all.slice(start, end);
  const heading = lines[0];
  // `## [1.5.0](url) (2026-07-15)` or the linkless `## 1.0.0 (2026-07-14)`.
  const meta = heading.match(
    /^##\s+(?:\[(?<linked>[^\]]+)\]\((?<url>[^)]+)\)|(?<plain>[^\s(]+))\s*\((?<date>[^)]+)\)/,
  );
  if (!meta) return null;

  const notes = [];
  let section = '';
  for (const raw of lines.slice(1)) {
    const line = raw.trim();
    const sectionMatch = line.match(/^###\s+(.*)$/);
    if (sectionMatch) {
      section = sectionMatch[1].trim();
      continue;
    }
    const bulletMatch = line.match(/^[*-]\s+(.*)$/);
    if (bulletMatch) {
      const summary = bulletMatch[1]
        // Drop the trailing `([abcdef1](commit-url))` reference.
        .replace(/\s*\(\[[0-9a-f]+\]\([^)]*\)\)\s*$/i, '')
        .trim();
      if (summary) notes.push({ section, summary });
    }
  }

  return {
    version: meta.groups.linked ?? meta.groups.plain,
    date: (meta.groups.date ?? '').trim(),
    url: meta.groups.url ?? null,
    notes,
  };
}

/** Render the marker-delimited generated block for config.ts. */
function renderReleaseBlock(release) {
  const notes = release.notes
    .map((n) => `    { section: ${str(n.section)}, summary: ${str(n.summary)} },`)
    .join('\n');
  return [
    '// LATEST_RELEASE:start — generated by scripts/sync-version.mjs; do not edit by hand.',
    'export const LATEST_RELEASE: Release = {',
    `  version: ${str(release.version)},`,
    `  date: ${str(release.date)},`,
    `  url: ${release.url ? str(release.url) : 'null'},`,
    notes ? `  notes: [\n${notes}\n  ],` : '  notes: [],',
    '};',
    '// LATEST_RELEASE:end',
  ].join('\n');
}

/** Serialize a value as a single-quoted TypeScript string literal. */
function str(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}
