export const VERSION = '1.5.0';

/** A single changelog entry (one conventional-commit subject). */
export interface ReleaseNote {
  /** Section it appeared under in the changelog, e.g. 'Features' or 'Bug Fixes'. */
  section: string;
  /** Commit subject with the trailing commit-hash link stripped. */
  summary: string;
}

/** The most recent published release, shown in the "About" modal. */
export interface Release {
  version: string;
  /** Release date as an ISO calendar date (YYYY-MM-DD). */
  date: string;
  /** Link to the full changelog entry (GitHub compare/release), or null. */
  url: string | null;
  notes: ReleaseNote[];
}

// LATEST_RELEASE:start — generated by scripts/sync-version.mjs; do not edit by hand.
export const LATEST_RELEASE: Release = {
  version: '1.5.0',
  date: '2026-07-15',
  url: 'https://github.com/MiquelGomezCorral/HoneyHold/compare/v1.4.0...v1.5.0',
  notes: [
    { section: 'Features', summary: 'standardize finance input controls' },
    { section: 'Bug Fixes', summary: 'stabilize ledger table interactions' },
  ],
};
// LATEST_RELEASE:end

export const TEXT_LIMITS = {
  concept: 255,
  counterparty: 128,
  tag: 255,
} as const;

export const LEDGER_COLUMN_SPANS = {
  date: 1,
  concept: 2,
  counterparty: 2,
  tag: 1,
  account: 3,
  amount: 2,
  actions: 1,
} as const;

export const TOAST = {
  max_toasts: 5,
  duration_ms: 3000,
  exit_ms: 200,
}